small_point_lio:
  ros__parameters:
    lidar_topic: /mid360_front/lidar                 # 点云话题名
    imu_topic: /mid360_front/imu                      # IMU话题名
    lidar_type: livox_pointcloud2              # 雷达类型 livox_custom_msg, livox_pointcloud2, custom_mid360_driver, unilidar
    lidar_frame: mid360_front_frame                   # 雷达坐标系
    save_pcd: false
    tf_x: -0.0005
    tf_y: 0.143336
    tf_z: 0.353036
    tf_roll: -0.785398
    tf_pitch: 0.0
    tf_yaw: 0.0
    tf_parent_frame: base_link
    tf_child_frame: mid360_front_frame 

    mid2_tf_x:  0.0425
    mid2_tf_y: -0.17337
    mid2_tf_z: 0.40591
    mid2_tf_roll: 0.785398
    mid2_tf_pitch: 0.0
    mid2_tf_yaw: 0.0
    mid2_tf_parent_frame: base_link
    mid2_tf_child_frame: mid360_back_frame


small_gicp_relocalization:
  ros__parameters:
    num_threads: 4
    num_neighbors: 10
    global_leaf_size: 0.25
    registered_leaf_size: 0.25
    max_dist_sq: 1.0
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    robot_base_frame: base_link
    lidar_frame: mid360_front_frame 
    prior_pcd_file: /home/wele/ros_ws/src/Mapping-and-Relocalization/small_point_lio/pcd/scan.pcd
    init_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    input_cloud_topic: cloud_registered
