small_point_lio:
  ros__parameters:
    lidar_topic: /mid360_front/lidar                 # 点云话题名
    imu_topic: /mid360_front/imu                      # IMU话题名
    lidar_type: livox_pointcloud2              # 雷达类型 livox_custom_msg, livox_pointcloud2, custom_mid360_driver, unilidar
    lidar_frame: mid360_front_frame                     # 雷达坐标系
    save_pcd: true
    tf_x: 0.0025
    tf_y: -0.13509
    tf_z: 0.29325
    tf_roll: -0.785398
    tf_pitch: 0.0
    tf_yaw: 3.1415926
    tf_parent_frame: base_link
    tf_child_frame: mid360_front_frame
